version: '3.9'

services:
  db:
    image: postgres
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=authorization
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    
    volumes:
      - postgres_data:/var/lib/postgres/data

  app:
    container_name: user_api
    build: .
    volumes:
      - .:/code
    
    ports:
      - "8000:8000"
    
    depends_on:
      - db

volumes:
  postgres_data: